### PR TITLE
#21 Add previous / next event buttons during event okayvscj

### PR DESCRIPTION
**Pull request by nileshbhingaradiya**
Added previous and next event button in event list screen

### CODE REVIEW

**Comment by nileshbhingaradiya** [comment]
https://share.vidyard.com/watch/9V2QJ5ePKDo2gTR7QtqQn9?

**Comment by curtishall** [comment]
Change text to "Previous"

Looks good. Eventually we should add an image (left right arrow) instead of text

**Comment by nileshbhingaradiya** [comment]
> Change text to "Previous"
> 
> Looks good. Eventually we should add an image (left right arrow) instead of text

image

**Review by divsbhalala — COMMENTED** [review]
seems all good

**Pull request merged**
